### ISSUE TITLE
Proposal: Manually specifies the visibility of symbols with GCC

### ISSUE THREAD

**Issue by wroyca** [Klaim/build2-common-build-configs#1]
'-fvisibility=hidden' is not set by default in GCC, which means that symbols are exported and can be used outside the object file in which they are defined. We should consider '-fvisibility=hidden' to make symbols hidden by default so that the compiler can avoid exporting unnecessary symbols

**Comment by Klaim** [comment]
good point, I should think about more basic defaults like that that are a better idea than when not specified...

**Comment by wroyca** [comment]
Closing this as this repository is now unmaintained and experimental in nature
